language: ruby
sudo: false
cache: bundler
env:
  - CODECLIMATE_REPO_TOKEN=f4f81d748a096e09c69653599c0bc5770c58f42be42c0db5ee2c71fc8835ff9c
bundler_args: --without tools
script: bundle exec rake ci
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
